"""Trip Notes

Revision ID: 16bffb744f33
Revises: 8e12410a0b8e
Create Date: 2025-10-04 16:15:08.434221

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "16bffb744f33"
down_revision = "8e12410a0b8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip", schema=None) as batch_op:
        batch_op.drop_column("notes")

    # ### end Alembic commands ###
