"""Trip Archival Review

Revision ID: 4f837664b686
Revises: 23320f01d8ce
Create Date: 2025-10-09 19:02:32.979368

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "4f837664b686"
down_revision = "23320f01d8ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip", schema=None) as batch_op:
        batch_op.add_column(sa.Column("archival_review", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip", schema=None) as batch_op:
        batch_op.drop_column("archival_review")

    # ### end Alembic commands ###
