"""TripDay date feature

Revision ID: 54aec61bc15d
Revises: b6d707f9c35a
Create Date: 2025-10-22 14:41:46.343276

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "54aec61bc15d"
down_revision = "b6d707f9c35a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tripday", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dt", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tripday", schema=None) as batch_op:
        batch_op.drop_column("dt")

    # ### end Alembic commands ###
