"""settings display visited

Revision ID: 6d6d726c95eb
Revises: c6bf10b10d0a
Create Date: 2025-11-15 17:47:28.035717

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "6d6d726c95eb"
down_revision = "c6bf10b10d0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mode_display_visited", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("mode_display_visited")

    # ### end Alembic commands ###
