"""TripItem GPX

Revision ID: 8e12410a0b8e
Revises: 8775a65d510f
Create Date: 2025-09-20 19:21:18.294547

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "8e12410a0b8e"
down_revision = "8775a65d510f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tripitem", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gpx", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tripitem", schema=None) as batch_op:
        batch_op.drop_column("gpx")

    # ### end Alembic commands ###
