"""TripItem images link table

Revision ID: bbcac0ad52a6
Revises: 7eb80d1f723d
Create Date: 2026-07-22 21:34:24.026996

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bbcac0ad52a6"
down_revision = "7eb80d1f723d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tripitemimagelink",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["image.id"], name=op.f("fk_tripitemimagelink_image_id_image"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["tripitem.id"],
            name=op.f("fk_tripitemimagelink_item_id_tripitem"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("item_id", "image_id", name=op.f("pk_tripitemimagelink")),
    )
    with op.batch_alter_table("tripitemimagelink", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tripitemimagelink_item_id"), ["item_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tripitemimagelink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tripitemimagelink_item_id"))

    op.drop_table("tripitemimagelink")
    # ### end Alembic commands ###
