"""User Google API KEY

Revision ID: e75fca7d8759
Revises: 4fadf12fa98c
Create Date: 2025-11-01 16:10:13.277275

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "e75fca7d8759"
down_revision = "4fadf12fa98c"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("google_apikey", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("google_apikey")

    # ### end Alembic commands ###
