"""settings map_position

Revision ID: f8c71711abc6
Revises: 4915de611ccf
Create Date: 2025-11-25 21:42:23.837984

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "f8c71711abc6"
down_revision = "4915de611ccf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mode_map_position", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("mode_map_position")

    # ### end Alembic commands ###
