name: Bug Report
description: Report something that is not working as expected.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - itskovacs

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug you encountered"
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: "To Reproduce"
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: "List the steps to reproduce the bug"
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Describe the expected behavior"

  - type: input
    id: trip_version
    attributes:
      label: "TRIP Version"
      description: "Specify the version of the TRIP application you are using (if applicable)."
      placeholder: "e.g., 1.19.1"

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots (if applicable)"
      description: "Add screenshots to help explain your problem."
      placeholder: "Paste image URLs or describe screenshots"

  - type: dropdown
    id: browser
    attributes:
      label: "Browser"
      options:
        - "Chrome"
        - "Firefox"
        - "Edge"
        - "Safari"
        - "Opera"
        - "Other"

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      placeholder: "Additional information"

  - type: dropdown
    id: canyoudoit
    attributes:
      label: "Could you fix it?"
      description: "If yes, we can discuss it so you can open a PR."
      options:
        - "Yes - I am able to do it"
        - "Maybe - I can try with guidance"
        - "No - I can't implement it right now"
      default: 2
    validations:
      required: true

  - type: textarea
    id: canyoudoit_how
    attributes:
      label: "Fix plan (optional)"
      description: "A short plan is enough (UI, API, data model, edge cases)."
      placeholder: "Example: add a new setting, update validation, adjust UI form, etc."